sudo: false
language: ruby
script: bundle exec rake spec
rvm:
  - jruby-1.7.24
branches:
  only:
    - master
    - /-dev|-feature|-fix/
before_install:
  - ([ "$BUNDLER_VERSION" ] && gem uninstall bundler --all --force && gem install bundler -v "$BUNDLER_VERSION") || true
  - bundle --version
before_script:
  - export JRUBY_OPTS="$JRUBY_OPTS --server -Xcext.enabled=false -Xcompile.invokedynamic=false"
env:
  - BUNDLER_VERSION="~> 1.10"
matrix:
  include:
    - rvm: jruby-1.7.25
      env: JRUBY_OPTS="--1.8" BUNDLER_VERSION="~> 1.7.9" RAKE_VERSION="~> 10.2.2"
    - rvm: jruby-1.7.25
      env: JRUBY_OPTS="--1.9" BUNDLER_VERSION="~> 1.11.2" RAKE_VERSION="~> 10.3.2"
    - rvm: jruby-1.7.8
      env: JRUBY_OPTS="--1.8" BUNDLER_VERSION="~> 1.8.9" RAKE_VERSION="~> 10.1.1"
    - rvm: jruby-1.7.16
      env: JRUBY_OPTS="" BUNDLER_VERSION="~> 1.10.2" RAKE_VERSION="~> 10.4.2"
    - rvm: 1.8.7
      env: BUNDLER_VERSION="~> 1.6.9" RAKE_VERSION="~> 10.4.2"
    - rvm: 1.9.2
      env: BUNDLER_VERSION="~> 1.7.9" RAKE_VERSION="~> 10.5.0"
    - rvm: 1.9.3
      env: BUNDLER_VERSION="~> 1.8.9" RAKE_VERSION="~> 10.2.2"
    - rvm: jruby-1.7.25
      env: MAVEN_OPTS="-XX:MaxPermSize=128m"
      script: mvn clean verify
  allow_failures:
    - script: mvn clean verify
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
